DocMaker/urls.py
from django.conf.urls import handler404
from django.urls import path

from . import views





urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("subjectselection",views.subjectselection,name="subjectselection"),
    path("template",views.templateCreation,name="templateCreation"),
    path('addsubject',views.AddSubject,name="addSubject"),
    path('addExperiment',views.AddExperiment,name="addExperiment"),
    path('edit/<int:id>/',views.editExperiment,name="editExperiment")



]

djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings






urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("DocMaker.urls")),
]








urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

DocMaker/models.py
from django.db import models

from django.utils import timezone

import datetime

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass


class Subject(models.Model):
    subject_owner = models.ForeignKey(User, related_name='experiment_by', on_delete=models.CASCADE)
    subject_faculty = models.CharField(max_length=30, null=True, blank=True)
    subject_name = models.CharField(max_length=80, blank=True, null=True)
    semester = models.IntegerField()
    roll_no = models.CharField(max_length=30, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject_name




class Experiments(models.Model):
    experiment_name = models.ForeignKey(Subject, related_name='experiments_by_subjects', on_delete=models.CASCADE,
                                        null=True, blank=True)
    experiment_owner = models.ForeignKey("User", related_name="experiment_by_which_owner", on_delete=models.CASCADE)
    experiment_number = models.IntegerField(null=True, blank=True)
    aim = models.TextField(max_length=500)
    source_code = models.TextField(max_length=10000)
    image_one = models.ImageField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.aim

    @property
    def imageURL(self):
        try:
            url = self.image_one.url
        except:
            url = ''
        return url


class UserCurrentSelectedSubjects(models.Model):
    subject_selection_owner = models.ForeignKey(User, related_name='subject_selected_by', on_delete=models.CASCADE)
    selected_subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.selected_subject.subject_name

DocMaker/forms.py
from django import forms

from .models import UserCurrentSelectedSubjects, Subject, Experiments




class userCurrentSelectedSubjects(forms.ModelForm):
    class Meta:
        model = UserCurrentSelectedSubjects
        fields = ['selected_subject']
        labels = {

            'selected_subject': 'Subject Name'

        }





class addSubject(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['subject_faculty', 'subject_name', 'semester', 'roll_no']


class addExperiment(forms.ModelForm):
    class Meta:
        model = Experiments
        fields = ['experiment_name','experiment_number', 'aim', 'source_code', 'image_one']
        labels = {

            'experiment_name': 'Subject Name'

        }


class editExperimentForm(forms.ModelForm):
    class Meta:
        model = Experiments
        fields = ['aim', 'source_code']

DocMaker/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import User, UserCurrentSelectedSubjects, Experiments, Subject
from .forms import *

from docx.enum.text import WD_ALIGN_PARAGRAPH

from docx.enum.text import WD_ALIGN_PARAGRAPH
from docxtpl import DocxTemplate, InlineImage, R

from docx.shared import Inches, Mm
from docx.shared import Pt

from django.contrib.auth.decorators import login_required



from django.utils.encoding import smart_str
from django.templatetags.static import static

from wsgiref.util import FileWrapper

import os


import time






   


def index(request):
    experiments = Experiments.objects.all()
    experimentList = list()
    for experiment in experiments:
        if str(experiment.experiment_owner) == str(request.user):
            experimentList.append(experiment)

    context = {'experiments': experimentList}

    return render(request, "DockMaker/index.html", context)

@login_required
def editExperiment(request, id):
    experiment = Experiments.objects.get(pk=id)
    subjectName = experiment.experiment_name
    if request.method != 'POST':
        form = editExperimentForm({'aim': experiment.aim, 'source_code': experiment.source_code})

    else:
        experiment.aim = request.POST.get('aim')
        experiment.source_code = request.POST.get('source_code')
        experiment.save()
        return redirect('index')
    context = {'form': form, 'id': id, 'subject': subjectName}
    return render(request, "DockMaker/editExperiment.html", context)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "Dockmaker/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "DockMaker/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "DockMaker/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "DockMaker/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "DockMaker/register.html")

@login_required
def AddSubject(request):
    if request.method != 'POST':
        form = addSubject()
    else:
        form = addSubject(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.subject_owner = request.user
            new_form.save()
            return redirect('addExperiment')
    context = {'form': form}
    return render(request, "DockMaker/addSubject.html", context)

@login_required
def AddExperiment(request):
    subjects = Subject.objects.all()
    lst = []
    for subject in subjects:
        if str(subject.subject_owner) == str(request.user):
            print(subject.id)
            lst.append(subject)
    if request.method != 'POST':
        form = addExperiment()
    else:
        form = addExperiment(request.POST,request.FILES)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.experiment_owner = request.user
            new_form.save()
            return redirect('index')
    context = {'form': form, 'subjects': lst}
    return render(request, "DockMaker/addExperiment.html", context)

@login_required
def subjectselection(request):
    subjects = Subject.objects.all()
    lst = []
    for subject in subjects:
        if str(subject.subject_owner) == str(request.user):
            print(subject.id)
            lst.append(subject)
    if request.method != 'POST':
        form = userCurrentSelectedSubjects()
    else:
        form = userCurrentSelectedSubjects(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.subject_selection_owner = request.user
            new_form.save()
            return redirect('templateCreation')
    context = {'form': form,'subjects':lst}
    return render(request, "DockMaker/subjectselection.html", context)

@login_required
def templateCreation(request):
    subject_name = UserCurrentSelectedSubjects.objects.all()

    current_selected_subject = ''
    for subject in subject_name:
        if subject.subject_selection_owner == request.user:
            current_selected_subject = subject.selected_subject
            subject.delete()

    subject = Subject.objects.all()
    lst = list()
    for usersubject in subject:
        if str(usersubject.subject_owner) == str(request.user) and str(usersubject.subject_name) == str(
                current_selected_subject):
            lst.append(usersubject)

    experiments = Experiments.objects.all()
    experimentList = list()
    for experiment in experiments:
        if str(experiment.experiment_owner) == str(request.user) and str(experiment.experiment_name) == str(
                current_selected_subject):
            experimentList.append(experiment)
    content = list()
    con = list()
    doc1 = DocxTemplate(r'DocMaker/static/docfiles/Template_4.docx')
    path = "/DocMaker/static"
    for i in experimentList:
        d1, d2 = {}, {}
        print(f'Experiment number is : {i.experiment_number}')
        d1['Eno'] = i.experiment_number
        d1['exp'] = i.aim
        print(f'aim is : {i.aim}')
        d1['date'] = f'{i.timestamp}'[:10]
        print(f'date is : {i.timestamp}')
        d2['exp'] = i.experiment_number
        print(i.imageURL)
        d2['aim'] = i.aim
        d2['source_code'] = i.source_code
        if i.imageURL !='':
            d2['imageURL'] = InlineImage(doc1,f"DocMaker/static{i.imageURL}",width=Mm(107.1), height=Mm(111))
        d2['page_break'] = R('\f')
        content.append(d1)
        con.append(d2)

    # con = {
    #     'con': [{'exp': 1, 'aim': 'First', 'img': InlineImage(doc1, "D:\IMG.JPG", width=Mm(107.1), height=Mm(111)), },
    #             {'exp': 2, 'aim': 'Second', 'name': 'Wow1'}],
    #     'page_break': 'page break:'}
    # doc1.render(con)

    context = {"subject_name": lst[0].subject_name,
               "semester": lst[0].semester,
               "subject_faculty": lst[0].subject_faculty,
               "subject_owner": lst[0].subject_owner,
               "roll_no": lst[0].roll_no,
               "content": content,
               "con": con,


               }



    doc1.render(context,autoescape=True)
    # print(f"DocMaker/static{i.imageURL}")

    doc1.save(f'DocMaker/static/docfiles/{request.user}.docx')




    file_path = f'DocMaker/static/docfiles/{request.user}.docx'
    FilePointer = open(file_path,"rb")
    response = HttpResponse(FilePointer,content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document')
    response['Content-Disposition'] = f'attachment; filename={request.user}.docx'




    if os.path.isfile(file_path):
        os.remove(file_path)
        print("success")
    else:
        print("File doesn't exists!")

    return response

DocMaker/templates/DockMaker/addExperiment.html
{% extends "DockMaker/layout.html" %}

{% load bootstrap4 %}

{% block content %}


<form action="/addExperiment" method="post" class="form" enctype="multipart/form-data">
{% csrf_token %}



    {% if not subjects %}
        <div class="alert alert-warning">
            <strong>Warning!</strong> Not added any Subjects yet
         </div>

    {% endif %}



<div class="form-group"><label for="id_experiment_name">Subject Name</label><select name="experiment_name" class="form-control" title="" id="id_experiment_name" required>
    
            <option value="" selected="">---------</option>

                    {% for subject in subjects %}
            <option value="{{ subject.id }}">{{subject.subject_name}}</option>
                    {% endfor %}


  </select>  
</div>
<div class="form-group"><label for="id_experiment_number">Experiment number</label><input type="number" name="experiment_number" class="form-control" placeholder="Experiment number" title="" id="id_experiment_number" required></div>
<div class="form-group"><label for="id_aim">Aim</label><textarea name="aim" cols="40" rows="10" maxlength="500" class="form-control" placeholder="Aim" title=""  id="id_aim" required></textarea></div>
<div class="form-group"><label for="id_source_code">Source code</label><textarea name="source_code" cols="40" rows="10" maxlength="10000" class="form-control" placeholder="Source code" title="" required id="id_source_code"></textarea></div>
<div class="form-group"><label for="id_image_one">Image one</label><br><input type="file" name="image_one" accept="image/*" class="form-control-file" title="" id="id_image_one"></div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

{% endblock content %}

DocMaker/templates/DockMaker/addSubject.html
{% extends "DockMaker/layout.html" %}

{% load bootstrap4 %}

{% block content %}


<form action="{% url 'addSubject'  %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock content %}

DocMaker/templates/DockMaker/editExperiment.html
{% extends "DockMaker/layout.html" %}
{% load static %}
{%load bootstrap4%}

{% block content %}

    <h1>{{ subject }}</h1>
    <form action="{% url 'editExperiment' id  %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock content %}

DocMaker/templates/DockMaker/index.html
{% extends "DockMaker/layout.html" %}
{% load static %}
{%load bootstrap4%}

 {% block page_header %}
   <div class="jumbotron" id="main-container">
     <h1 class="display-3">Track your Lab.</h1>

    <p>Make your own Lab Log, and keep a list of the experiments you're learning about.
       Whenever you get a new experiment,
       make an entry what you've done and when time gets to submit your lab file, download it pre-prepared fron here.
    </p>
   <p><b>APDocxBuilder</b></p>
    {%  if request.user.is_authenticated %}


        {% if not experiments %}

                <a href="{%  url 'addSubject' %}"><button class="btn btn-lg btn-primary">You have not added any experiments yet</button>
        {% else %}

           <button  class="btn btn-lg btn-primary all-experiment-button">Show Experiments</button>


        {% endif %}


    {% else %}
        <a class="btn btn-lg btn-primary" href="{% url 'register'%}"
      role="button">Register &raquo;</a>
    {% endif %}


  </div>
 <div id="experiment-section">
     {%  if request.user.is_authenticated %}


          {% if not experiments %}




        {% else %}
                <a href="{% url 'subjectselection' %}"><button style= " float :right;" class="btn btn-lg btn-primary">Download</button></a>
                  <h2>All Experiments</h2> 
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Experiment number</th>
                        <th>Subject</th>
                        <th>Aim</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for experiment in experiments %}
                      <tr>
                        <td>{{ experiment.experiment_number }}</td>
                        <td>{{ experiment.experiment_name}}</td>
                          <td><a href="{% url 'editExperiment' experiment.id %}">{{ experiment.aim }}</a></td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
        {% endif %}
    {% else %}

    {% endif %}


 </div>








{% endblock page_header  %}

DocMaker/templates/DockMaker/layout.html
{% load static %}
{%load bootstrap4%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Doc Maker</title>
     {% bootstrap_css %}
     {% bootstrap_javascript jquery='full' %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'DockMaker/styles.css' %}" rel="stylesheet">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}">APDocxBuilder</a>

            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}

                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'addSubject' %}">Add Subject</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'addExperiment' %}">Add Experiment</a>
                    </li>
                    <li class="nav-item">
                        <a  class="nav-link" href="{% url 'logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
              {% block page_header %} {% endblock page_header%}
            </div>
            <div>
              {% block content %}{% endblock content%}
            </div>
        </main>

          {% block script %}
                <script src="{% static 'DockMaker/index.js' %}"></script>
          {% endblock %}
    </body>
</html>

DocMaker/templates/DockMaker/login.html
{% extends "DockMaker/layout.html" %}

{% block content %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock content %}

DocMaker/templates/DockMaker/register.html
{% extends "DockMaker/layout.html" %}
{% load static %}
{%load bootstrap4%}

{% block content %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock content %}

DocMaker/templates/DockMaker/subjectselection.html
{% extends "DockMaker/layout.html" %}

{% load bootstrap4 %}

{% block content %}


<form action="/subjectselection" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group"><label for="id_selected_subject">Subject Name</label><select name="selected_subject" class="form-control" title="" required="" id="id_selected_subject">
  <option value="" selected="">---------</option>

  {% for subject in subjects %}

  <option value="{{subject.id}}">{{subject.subject_name}}</option>

  {% endfor %}

  

</select></div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

{% endblock content %}